# nexus-k8s.yaml

# --- Namespace: Define the namespace for all Nexus resources ---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus-ns
---

# --- ServiceAccount: Create a service account for Nexus ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-ksa
  namespace: nexus-ns
  annotations:
    iam.gke.io/gcp-service-account: sa-nexus@nexus-test-466602.iam.gserviceaccount.com

---

# --- Service: Exposes Nexus to your local machine ---
# Service to expose Nexus to the internet
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus-ns
  labels:
    app: nexus
spec:
  type: LoadBalancer
  ports:
    - port: 8081 
      targetPort: 8081 
      nodePort: 30081 
  selector:
    app: nexus

---

# --- PersistentVolumeClaim: Requests storage for Nexus data ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus-ns 
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 8Gi

---

# --- Deployment: Defines the desired state for our Nexus pod ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: nexus-ns
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      serviceAccountName: nexus-ksa 
      securityContext:
        runAsUser: 200    
        fsGroup: 200      
      containers:
        - name: nexus
          image: us-central1-docker.pkg.dev/nexus-test-466602/nexus-repo/nexus-custom:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
