# --- Service: Exposes Nexus to your local machine ---
# Service to expose Nexus to the internet
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus-ns
  labels:
    app: nexus
spec:
  type: LoadBalancer
  ports:
    - port: 8081 
      targetPort: 8081 
      nodePort: 30081 
  selector:
    app: nexus
