# --- ServiceAccount: Create a service account for Nexus ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-ksa
  namespace: nexus-ns
  annotations:
    iam.gke.io/gcp-service-account: sa-nexus@nexus-test-466602.iam.gserviceaccount.com